-- Basic
require("core.env")
require("core.plugins")
require("core.configs")
require("core.mappings")
require("core.colors")

-- Plugins
require("plugins.treesitter")
require("plugins.neodev") -- should be before lsp
require("plugins.lsp")
require("plugins.cmp")
require("plugins.mason")
require("plugins.telescope")
require("plugins.devicons")
require("plugins.nvimtree")
require("plugins.dashboard")
require("plugins.nullls")
require("plugins.lualine")
require("plugins.bufferline")
require("plugins.whichkey")
require("plugins.autopairs")
require("plugins.autotag")
require("plugins.surround")
require("plugins.comment")
require("plugins.gitsigns")
require("plugins.diffview")
require("plugins.toggleterm")
-- require('plugins.copilot')
require("plugins.chatgpt")
